### ISSUE TITLE
What are the chances of me getting banned?

### ISSUE THREAD

**Issue by rjworks** [rjruizfdez/insta-unfollow#36]
Instagram bans too much requests. Does this program do anything about that? What are the chances of me getting banned?

**Comment by ricardojoserf** [comment]
Hi @rjworks !!! It depends on the account. If it is a personal account and you have used it for years, there is not problem if you use one day every some months (which is my case). In general, I would advice not to use it a lot or you will get banned, but I can not tell you an exact answer because I do not use it. But Instagram becomes more and more aware of these scripts so I would not use it frequently! I will close this as it is not a bug :)
